### PR TITLE
database structure implemented

### LINKED ISSUE #2: Create Database
[sqLite browser](https://sqlitebrowser.org/)
- create database
- create tables

### PR DESCRIPTION
**Pull request by Imroboboy**
resolves #2

### CODE REVIEW

**Review by Geordous-Huxwell — CHANGES_REQUESTED** [review]
guess I can't review a binary file. Can you add a screenshot from the sqlite db program that shows the schema you created the file with to the PR description?

**Comment by Imroboboy** [comment]
> guess I can't review a binary file. Can you add a screenshot from the sqlite db program that shows the schema you created the file with to the PR description?
This lookin good, chief?
image

**Review by jgill204 — APPROVED** [review]

**Comment by Srafington** [comment]
Should there not be referential constraints? Items should not exist that do not have suppliers

**Comment by Imroboboy** [comment]
Updated references:
image

**Review by Geordous-Huxwell — APPROVED** [review]

**Review by Srafington — APPROVED** [review]

**Pull request merged**
